version: 0.2

env:
 parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url

phases: 
 install: 
  runtime-versions:
   python: 3.11


 pre_build:
  commands:
   - pip install -r /AWSCode_Build/requiremnts.txt
 build: 
  commands:
   - cd /AWSCode_Build
   - echo "Building docker image"
   - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest" .
   - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest"
 post_build: 
  commands:
   - echo "Build successful"
  
